### ISSUE TITLE
could not find the script folder

### ISSUE THREAD

**Issue by Fran6Bo** [Apress/agile-ai-in-pharo#1]
Bonjour,

I really like your Agile Artificial Intelligence in Pharo book. I am not new to both AI and Smalltalk and I find your material just perfect to experiment and learn. Great work for making things fun and easy

I was able to download and install  the src material  but could not find the /scripts folder that is mentioned in the book page xix.

Best Regards

Francis

**Comment by bergel** [comment]
Hi Francis,

Simply forgot to do a `git push`. Thanks for your issue.
If you happens to pass by Santiago (Chile) or Nice (France), let me now. You deserve a drink :-)

Merci,
Alexandre
